### ISSUE TITLE
Delete snapshot

### ISSUE THREAD

**Issue by omexlu** [omerh/hetzner-hcloud-snapshots#1]
Hi,

Does this delete the oldest snapshot on the row?

Thanks.

**Comment by omerh** [comment]
yes.
The api gives a orderer by date list.

**Comment by omexlu** [comment]
Hi,

Can you please supply me the modified backup.sh for using on bash without docker?

I really want to use them but I think the backup.sh must be modificated? 

Thanks.

**Comment by omerh** [comment]
You just need to add the following ENV variables (or set them as variables in the script

```bash
HCLOUD_TOKEN=[your hetzner token]
KEEP=3
```

**Comment by omexlu** [comment]
You mean that way? So 3 Snapshots will be keeped? 

```
#!/bin/bash

set -e

# personal settings
HCLOUD_TOKEN=[your hetzner token]
KEEP=3

# set the amount of images to keep
KEEP_SNAPSHOTS=${KEEP:-2}

# get all server ids in project
SERVERSID=$(hcloud server list -o noheader -o columns=id)

function make_snapshot {
  echo "Creating snapshot to server id $1"
  hcloud server create-image --type snapshot --label id=$1 --description server-$1 --poll-interval 0 $1
}

function rotate_snapshots {
  echo "Check if rotate is needed"
  if [[ `hcloud image list --type snapshot --selector id=$1 -o noheader -o columns=id | wc -l | xargs` > $KEEP_SNAPSHOTS ]]; then
    echo "Deleting last snapshot"
    SNAPSHOTID=$(hcloud image list --type snapshot --selector id=$1 -o noheader -o columns=id | head -1)
    hcloud image delete $SNAPSHOTID
  else 
    echo "No need to delete snapshot"
  fi
}

for ID in $SERVERSID; do
  echo "working on server id $ID"
  make_snapshot $ID
  rotate_snapshots $ID
done
```

**Comment by omerh** [comment]
yes

**Comment by omexlu** [comment]
Thank you sir 😊

Maybe change this line:
`echo "Deleting last snapshot"`
to
`echo "Deleting oldest snapshot"`

Because that little bit confusing.

Ps. Do you shutdown your servers bevor doing Snapshots?

**Comment by omerh** [comment]
No, Im leaving the server up.
the snapshot process exit code say if the snapshot works

**Comment by omexlu** [comment]
Hello,

Works great i had to do context use because of multiple scripts and multiple projects to get it running correctly. 

Do you know how I can grep then status (success or error) on the end for further notifications?

**Comment by omerh** [comment]
according to exit code (its running sync) and API returns the result.
at least that is the answer I've got from their developers https://github.com/hetznercloud/cli/issues/284
